[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "henry"
authors = [{name = "Eelis Peltola", email = "eelis.peltola@aalto.fi"}]
dynamic = ["version", "description"]
